### ISSUE TITLE
Can't run on JRE 1.8

### ISSUE THREAD

**Issue by ts2kt** [Kotlin/dukat#1]
```
$ npm i dukat -g
$ dukat some.d.ts 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jetbrains/dukat/nashorn/DocumentCache has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.dukat.compiler.TranslatorGraal.<init>(translator.kt:142)
	at org.jetbrains.dukat.compiler.TranslatorKt.createGraalTranslator(translator.kt:153)
	at org.jetbrains.dukat.cli.CliKt.main(cli.kt:172)
```
```
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```
```
macOS 10.13.6
```

**Comment by Schahen** [comment]
Resolved in
https://github.com/Kotlin/dukat/commit/5d5b441fa2798cfb899f56870a6c3cbac5142181
