### ISSUE TITLE
kotlin-js-demo-1.3.50 compile error

### ISSUE THREAD

**Issue by XQDD** [Kotlin/dukat#105]
#### System:  win10 x64

```log
> Task :kotlinNpmInstall
tests

> Task :generateExternals FAILED
/mnt/d/me/code/code/kotlin/hello/hello_js/build/js/packages/hello_js/node_modules/.bin/dukat:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateExternals'.
```

**Comment by sgarfinkel** [comment]
This appears to be a problem on Windows platforms, due to the fact the incorrect binary is being called (as it is hardcoded): https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/dukat/DukatExecutor.kt#L42

Not sure this can be fixed without upstream changes.

**Comment by sgarfinkel** [comment]
@XQDD I am also experiencing this on Windows. But I notice your path is Unix. Are you running this from the WSL?

**Comment by snrostov** [comment]
This looks like Kotlin/JS Gradle plugin bug, not dukat. I'm create issue in youtrack for that: https://youtrack.jetbrains.com/issue/KT-33736

**Comment by XQDD** [comment]
@snrostov Both WSL and Windows would occur this issue in the Windows file system, I tried to 
 place it in Linux File system with WSL, some times it would not occur. But this issue always occur in windows.

**Comment by Syrou** [comment]
Same

**Comment by lamba92** [comment]
Related? https://youtrack.jetbrains.com/issue/KT-34389
