### ISSUE TITLE
Fail convert https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types/axios/axios.d.ts

### ISSUE THREAD

**Issue by ScottHuangZL** [Kotlin/dukat#159]
**NullPointerException: null**
    at Object.throwNPE (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\kotlin.js:3325:11)
    at TsClassToKt.visitClassDeclaration_4wvyue$ (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:1956:114)
    at TypeScriptToKotlin.visitClassDeclaration_4wvyue$ (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:2494:16)
    at visitNode (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:1864:15)
    at C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:1840:7
    at visitEachNode (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\node_modules\_typescript@2.0.10@typescript\lib\typescript.js:8343:30)
    at forEachChild (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\node_modules\_typescript@2.0.10@typescript\lib\typescript.js:8503:24)
    at forEachChild_0 (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:1844:5)
    at TypeScriptToKotlinBase.visitList_uvf806$ (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:2846:5)
    at TypeScriptToKotlin.visitList_uvf806$ (C:\Users\scott_huang\AppData\Roaming\npm\node_modules\ts2kt\ts2kt.js:2720:56)

**Comment by Schahen** [comment]
This issues was migrated from the `ts2kt` project which is deprecated in favour of a newer tool, `dukat`. I'm happy to announce that in dukat axios declarations are translated and compiling.
