### ISSUE TITLE
Reference paths seem to be resolved relative to filesystem root

### ISSUE THREAD

**Issue by hedgehog1029** [Kotlin/dukat#170]
Trying to convert the [Node.js bindings](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node) which uses the `/// <reference path="globals.d.ts" />` syntax for including other files. It seems that ts2kt tries to look for references relative to the filesystem root, as per this stacktrace:

```
types/node (master) ➥ ts2kt -d kotlin index.d.ts 
ts2kt version: 0.1.3
Converting index.d.ts
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/base.d.ts'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at getScriptSnapshotFromFile (/usr/lib/node_modules/ts2kt/ts2kt.js:5398:46)
    at translate (/usr/lib/node_modules/ts2kt/ts2kt.js:5623:21)
    at translateToDir (/usr/lib/node_modules/ts2kt/ts2kt.js:5177:26)
    at main (/usr/lib/node_modules/ts2kt/ts2kt.js:5387:5)
    at /usr/lib/node_modules/ts2kt/ts2kt.js:6243:3
    at Object.<anonymous> (/usr/lib/node_modules/ts2kt/ts2kt.js:6246:2)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
```

The reference paths don't have the preceding slash so something in ts2kt seems to be adding it.

**Comment by Schahen** [comment]
@steelxt this issues was ported from ts2kt which is deprecated. In dukat this works.
