### ISSUE TITLE
TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by SUPERCILEX** [Kotlin/dukat#197]
I'm using the `kotlin.js.experimental.generateKotlinExternals=true` property and using the latest version with `rootProject.kotlinNodeJs.versions.dukat.version = "0.0.23"`. The converter fails with this dependency: `implementation(npm("firebase", "7.5.0"))`.

```
> Task :web:site:generateExternals FAILED
/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129391
                return moduleSymbol.declarations[0].name.getText();
                                                         ^

TypeError: Cannot read property 'getText' of undefined
    at AstConverter.resolveAmbientModuleName (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129391:58)
    at AstConverter.convertModule (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129410:43)
    at AstConverter.convertStatement (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129369:40)
    at AstConverter.convertStatements (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129380:40)
    at AstConverter.createSourceFileDeclaration (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:128782:33)
    at /home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:128817:32
    at Set.forEach (<anonymous>)
    at ResourceFetcher.forEachReference (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129570:26)
    at AstConverter.createSourceSet (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:128816:24)
    at translateFile (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:146:38)

FAILURE: Build failed with an exception.
```

**Comment by SUPERCILEX** [comment]
@Schahen Here's the project that fails: https://github.com/MasonAmerica/mason-check-in-kiosk. You'll have to uncomment the `gradle.properties`.

**Comment by SUPERCILEX** [comment]
Still fails on `v0.0.24`:
```
TypeError: Cannot read property 'getText' of undefined
    at AstConverter.resolveAmbientModuleName (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129556:58)
    at AstConverter.convertModule (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129575:43)
    at AstConverter.convertStatement (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129507:45)
    at AstConverter.convertStatements (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:129529:65)
    at AstConverter.createSourceFileDeclaration (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:128830:33)
    at SourceBundleBuilder.createFileDeclarations (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:162:44)
    at SourceBundleBuilder.createSourceSet (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:154:21)
    at /home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:174:69
    at Array.map (<anonymous>)
    at SourceBundleBuilder.createBundle (/home/mason/Desktop/mason-check-in-kiosk/build/js/node_modules/dukat/lib/converter.js:173:32)
```

**Comment by SUPERCILEX** [comment]
@Schahen Can this please be prioritized? Dukat is completely broken for me with this bug. :disappointed:

**Comment by lamba92** [comment]
I managed to generate bindings for Firebase 7.7.0. There were few errors so i manually edited them and zipped them [here](https://github.com/lamba92/firebase-multiplatform/blob/master/firebasejs_kotlin_externals.zip)! Hope it may helps in the meantime.

**Comment by ScottPierce** [comment]
I'm seeing this error as well while trying to use gradle's auto generated dukat bindings for firebase-functions and firebase-admin. The exceptions are a little different though. 

I'm also running `rootProject.kotlinNodeJs.versions.dukat.version = "0.0.28"`

```
/build/js/node_modules/dukat/lib/converter.js:1222
            finally { if (e_11) throw e_11.error; }
                                ^

TypeError: Cannot read property 'getText' of undefined
    at AstConverter.resolveAmbientModuleName (/Users/scott.pierce/workspace/dev.scottpierce/behind-the-wheel/btw-mpp/build/js/node_modules/dukat/lib/converter.js:1230:58)
    at AstConverter.convertModule (/Users/scott.pierce/workspace/dev.scottpierce/behind-the-wheel/btw-mpp/build/js/node_modules/dukat/lib/converter.js:1249:43)
    at AstConverter.convertTopLevelStatement (/Users/scott.pierce/workspace/dev.scottpierce/behind-the-wheel/btw-mpp/build/js/node_modules/dukat/lib/converter.js:1178:45)
    at AstConverter.convertStatements (/Users/scott.pierce/workspace/dev.scottpierce/behind-the-wheel/btw-mpp/build/js/node_modules/dukat/lib/converter.js:1203:65)
    at AstConverter.createModuleFromSourceFile (/Users/scott.pierce/workspace/dev.scottpierce/behind-the-wheel/btw-mpp/build/js/node_modules/dukat/lib/converter.js:469:189)
    at AstConverter.createSourceFileDeclaration (/Users/scott.pierce/workspace/dev.scottpierce/behind-the-wheel/btw-mpp/build/js/node_modules/dukat/lib/converter.js:472:86)
    at SourceBundleBuilder.createFileDeclarations (/Users/scott.pierce/workspace/dev.scottpierce/behind-the-wheel/btw-mpp/build/js/node_modules/dukat/lib/converter.js:169:49)
    at SourceBundleBuilder.createSourceSet (/Users/scott.pierce/workspace/dev.scottpierce/behind-the-wheel/btw-mpp/build/js/node_modules/dukat/lib/converter.js:161:21)
    at /Users/scott.pierce/workspace/dev.scottpierce/behind-the-wheel/btw-mpp/build/js/node_modules/dukat/lib/converter.js:195:69
    at Array.map (<anonymous>)
```

**Comment by audkar** [comment]
What scope is of this problem fix? Does it require bigger changes or not a priority atm?

**Comment by epabst** [comment]
ETA?

**Comment by SUPERCILEX** [comment]
Closing old issues.

**Comment by ScottPierce** [comment]
@SUPERCILEX But is it fixed? I don't think that dukat has been a focus for a while, and this shouldn't be closed if it's not fixed.

**Comment by SUPERCILEX** [comment]
Nah, I don't think it's fixed. I'll reopen.
