### ISSUE TITLE
KotlinNullPointerException from jsTestGenerateExternals

### ISSUE THREAD

**Issue by epabst** [Kotlin/dukat#203]
In processing npm("firebase", "6.2.0"), I got this error:
```
> Task :jsTestGenerateExternals
Exception in thread "main" kotlin.KotlinNullPointerException
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.resolveParameters(resolveDefaultTypeParams.kt:34)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerTypeDeclaration(resolveDefaultTypeParams.kt:55)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerParameterValue(DeclarationLowering.kt:47)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerParameterValue(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerParameterValue(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerUnionTypeDeclaration(DeclarationTypeLowering.kt:108)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerUnionTypeDeclaration(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerParameterValue(DeclarationLowering.kt:49)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerParameterValue(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerParameterValue(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerParameterDeclaration(DeclarationTypeLowering.kt:131)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerParameterDeclaration(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerMethodSignatureDeclaration(DeclarationTypeLowering.kt:85)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerMethodSignatureDeclaration(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerMemberDeclaration(DeclarationTypeLowering.kt:73)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerMemberDeclaration(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerInterfaceDeclaration(DeclarationTypeLowering.kt:145)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerInterfaceDeclaration(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerClassLikeDeclaration(DeclarationLowering.kt:59)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerClassLikeDeclaration(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerClassLikeDeclaration(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerTopLevelDeclaration(DeclarationLowering.kt:71)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerTopLevelDeclaration(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerTopLevelDeclaration(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerTopLevelDeclarations(DeclarationLowering.kt:80)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerTopLevelDeclarations(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerTopLevelDeclarations(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerDocumentRoot(DeclarationLowering.kt:85)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerDocumentRoot(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerDocumentRoot(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerTopLevelDeclaration(DeclarationLowering.kt:72)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerTopLevelDeclaration(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerTopLevelDeclaration(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerTopLevelDeclarations(DeclarationLowering.kt:80)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerTopLevelDeclarations(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerTopLevelDeclarations(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerDocumentRoot(DeclarationLowering.kt:85)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerDocumentRoot(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerDocumentRoot(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerTopLevelDeclaration(DeclarationLowering.kt:72)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerTopLevelDeclaration(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerTopLevelDeclaration(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerTopLevelDeclarations(DeclarationLowering.kt:80)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerTopLevelDeclarations(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerTopLevelDeclarations(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerDocumentRoot(DeclarationLowering.kt:85)
	at org.jetbrains.dukat.tsLowerings.DeclarationTypeLowering$DefaultImpls.lowerDocumentRoot(DeclarationTypeLowering.kt)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParams.lowerDocumentRoot(resolveDefaultTypeParams.kt:15)
	at org.jetbrains.dukat.tsLowerings.DeclarationLowering$DefaultImpls.lowerDocumentRoot$default(DeclarationLowering.kt:84)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParamsKt.resolveDefaultTypeParams(resolveDefaultTypeParams.kt:77)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParamsKt.resolveDefaultTypeParams(resolveDefaultTypeParams.kt:80)
	at org.jetbrains.dukat.tsLowerings.ResolveDefaultTypeParamsKt.resolveDefaultTypeParams(resolveDefaultTypeParams.kt:82)
	at org.jetbrains.dukat.ts.translator.TypescriptInputTranslator$DefaultImpls.lower(TypescriptInputTranslator.kt:53)
	at org.jetbrains.dukat.ts.translator.JsRuntimeByteArrayTranslator.lower(JsRuntimeByteArrayTranslator.kt:10)
	at org.jetbrains.dukat.ts.translator.TypescriptInputTranslator$DefaultImpls.lower(TypescriptInputTranslator.kt:89)
	at org.jetbrains.dukat.ts.translator.JsRuntimeByteArrayTranslator.lower(JsRuntimeByteArrayTranslator.kt:10)
	at org.jetbrains.dukat.ts.translator.JsRuntimeByteArrayTranslator.translate(JsRuntimeByteArrayTranslator.kt:21)
	at org.jetbrains.dukat.ts.translator.JsRuntimeByteArrayTranslator.translate(JsRuntimeByteArrayTranslator.kt:10)
	at org.jetbrains.dukat.translatorString.TranslateModuleKt.translateModule(translateModule.kt:125)
	at org.jetbrains.dukat.cli.CliKt.compile(cli.kt:42)
	at org.jetbrains.dukat.cli.CliKt.main(cli.kt:260)
```

**Comment by dwlizlo** [comment]
Got the same error for **@types/victory**.

**Comment by alxgrk** [comment]
same for "@types/react", version 16.9.0

**Comment by ivakub** [comment]
As was described in https://github.com/Kotlin/dukat/issues/200 you can change the version of Dukat in your Gradle file:

build.gradle.kts
```
import org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension
import org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin

rootProject.plugins.withType<NodeJsRootPlugin> {
    (extensions[NodeJsRootExtension.EXTENSION_NAME] as NodeJsRootExtension).apply {
        versions.dukat.version = "0.0.24"
    }
}
```

or in build.gradle
```
kotlin.js.experimental.generateKotlinExternals = true
```

**Comment by ivakub** [comment]
@alxgrk I failed to reproduce your problem. Can you create a separate issue with a description?

**Comment by alxgrk** [comment]
sure @ivakub, done by creation of #209
