### ISSUE TITLE
TypeError: Cannot read property 'fileName' of undefined

### ISSUE THREAD

**Issue by hshar7** [Kotlin/dukat#208]
```
$ dukat ../../../node_modules/web3-eth-contract/types/index.d.ts
/usr/lib/node_modules/dukat/lib/converter.js:128828
        var packageNameFragments = sourceFile.fileName.split("/");
                                              ^

TypeError: Cannot read property 'fileName' of undefined
    at AstConverter.createSourceFileDeclaration (/usr/lib/node_modules/dukat/lib/converter.js:128828:47)
    at SourceBundleBuilder.createFileDeclarations (/usr/lib/node_modules/dukat/lib/converter.js:162:44)
    at /usr/lib/node_modules/dukat/lib/converter.js:167:19
    at Array.forEach (<anonymous>)
    at SourceBundleBuilder.createFileDeclarations (/usr/lib/node_modules/dukat/lib/converter.js:166:14)
    at /usr/lib/node_modules/dukat/lib/converter.js:167:19
    at Array.forEach (<anonymous>)
    at SourceBundleBuilder.createFileDeclarations (/usr/lib/node_modules/dukat/lib/converter.js:166:14)
    at /usr/lib/node_modules/dukat/lib/converter.js:167:19
    at Array.forEach (<anonymous>)
```

**Comment by alxgrk** [comment]
seems to be the same problem as in as #207

**Comment by hshar7** [comment]
In favor of #207
