### ISSUE TITLE
@types/d3: Process 'Generating Kotlin/JS external declarations' returns 1

### ISSUE THREAD

**Issue by Jolanrensen** [Kotlin/dukat#229]
Trying to import the types of d3.js like `implementation(npm("@types/d3"))` results in the following Error:
```
            finally { if (e_9) throw e_9.error; }
                               ^

TypeError: Cannot read property 'getText' of undefined
    at AstConverter.resolveAmbientModuleName (/mnt/HardDisk/Projects/dukatGradleDemo/build/js/node_modules/dukat/lib/converter.js:129556:58)
    at AstConverter.convertModule (/mnt/HardDisk/Projects/dukatGradleDemo/build/js/node_modules/dukat/lib/converter.js:129575:43)
    at AstConverter.convertStatement (/mnt/HardDisk/Projects/dukatGradleDemo/build/js/node_modules/dukat/lib/converter.js:129507:45)
    at AstConverter.convertStatements (/mnt/HardDisk/Projects/dukatGradleDemo/build/js/node_modules/dukat/lib/converter.js:129529:65)
    at AstConverter.createSourceFileDeclaration (/mnt/HardDisk/Projects/dukatGradleDemo/build/js/node_modules/dukat/lib/converter.js:128830:33)
    at SourceBundleBuilder.createFileDeclarations (/mnt/HardDisk/Projects/dukatGradleDemo/build/js/node_modules/dukat/lib/converter.js:162:44)
    at SourceBundleBuilder.createSourceSet (/mnt/HardDisk/Projects/dukatGradleDemo/build/js/node_modules/dukat/lib/converter.js:154:21)
    at /mnt/HardDisk/Projects/dukatGradleDemo/build/js/node_modules/dukat/lib/converter.js:174:69
    at Array.map (<anonymous>)
    at SourceBundleBuilder.createBundle (/mnt/HardDisk/Projects/dukatGradleDemo/build/js/node_modules/dukat/lib/converter.js:173:32)

Execution failed for task ':generateExternals'.
> Process 'Generating Kotlin/JS external declarations' returns 1
```

**Comment by whyoleg** [comment]
Any news on this?
