### ISSUE TITLE
Exception running dukat in ide with gradle

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/dukat#234]
`implementation(npm("firebase-functions", "3.3.0"))`
`rootProject.kotlinNodeJs.versions.dukat.version = "0.0.28"`
Gradle 6.1.1

```
> Task :firebase-functions:generateExternals
Exception in thread "main" java.lang.StackOverflowError
        at org.jetbrains.dukat.astCommon.QualifierEntity.hashCode(NameEntity.kt)
        at org.jetbrains.dukat.astCommon.QualifierEntity.hashCode(NameEntity.kt)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.LinkedHashMap.get(LinkedHashMap.java:440)
        at org.jetbrains.dukat.model.commonLowerings.ModelContext.unalias(ModelContext.kt:95)
        at org.jetbrains.dukat.model.commonLowerings.ModelContext.getParents(ModelContext.kt:141)
        at org.jetbrains.dukat.model.commonLowerings.ModelContext.getAllParents(ModelContext.kt:149)
        at org.jetbrains.dukat.model.commonLowerings.ModelContext.getAllParents(ModelContext.kt:150)
        at org.jetbrains.dukat.model.commonLowerings.ModelContext.getAllParents(ModelContext.kt:150)
        at org.jetbrains.dukat.model.commonLowerings.ModelContext.getAllParents(ModelContext.kt:150)
        at org.jetbrains.dukat.model.commonLowerings.ModelContext.getAllParents(ModelContext.kt:150)
        at org.jetbrains.dukat.model.commonLowerings.ModelContext.getAllParents(ModelContext.kt:150)
        at org.jetbrains.dukat.model.commonLowerings.ModelContext.getAllParents(ModelContext.kt:150)
        ...
```

I cut the stacktrace off because it's a stackoverflow and repeats itself over and over and over.

**Comment by sakebook** [comment]
Same error from cli.

**Comment by Schahen** [comment]
see also - https://youtrack.jetbrains.com/issue/KT-37108

**Comment by audkar** [comment]
This is critical for sure :sob: partially generated output would be better then complete failure

**Comment by ScottPierce** [comment]
I just tried this with `0.5.4`, and it still happens. here is a comment that has a complete repro project: https://github.com/Kotlin/dukat/issues/322#issuecomment-653673019

**Comment by DRSchlaubi** [comment]
Is there any sort of workaround for this. have tired converting discord.js and got the same error

**Comment by ScottPierce** [comment]
@DRSchlaubi  - Dukat seems to be dead. This release was originally supposed to come in August 2020 - https://github.com/Kotlin/dukat/milestone/15
