### ISSUE TITLE
Crash while running for react-native

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/dukat#244]
I tried running Dukat against the react-native types that I found in my `node_modules/@types` directory.

Here is my command:
```
dukat -d ./output ./react-native/node_modules/\@types/react-native/index.d.ts 
```

Here is the crash I got:
```
/usr/local/lib/node_modules/dukat/lib/converter.js:1222
            finally { if (e_11) throw e_11.error; }
                                ^

TypeError: Cannot read property 'getText' of undefined
    at AstConverter.resolveAmbientModuleName (/usr/local/lib/node_modules/dukat/lib/converter.js:1230:58)
    at AstConverter.convertModule (/usr/local/lib/node_modules/dukat/lib/converter.js:1249:43)
    at AstConverter.convertTopLevelStatement (/usr/local/lib/node_modules/dukat/lib/converter.js:1178:45)
    at AstConverter.convertStatements (/usr/local/lib/node_modules/dukat/lib/converter.js:1203:65)
    at AstConverter.createModuleFromSourceFile (/usr/local/lib/node_modules/dukat/lib/converter.js:469:189)
    at AstConverter.createSourceFileDeclaration (/usr/local/lib/node_modules/dukat/lib/converter.js:472:86)
    at SourceBundleBuilder.createFileDeclarations (/usr/local/lib/node_modules/dukat/lib/converter.js:169:49)
    at /usr/local/lib/node_modules/dukat/lib/converter.js:177:23
    at Array.forEach (<anonymous>)
    at SourceBundleBuilder.createFileDeclarations (/usr/local/lib/node_modules/dukat/lib/converter.js:176:18)
```

**Comment by ScottPierce** [comment]
It looks like I filed an issue against this in 2017. At least it's a different crash now though. https://github.com/Kotlin/dukat/issues/182

**Comment by ScottPierce** [comment]
@Schahen Is it worth testing to see if 0.5.0 fixes this?

**Comment by shabunc** [comment]
If this works for you in that sense that it's not failing during translation, I'm closing this one and will work on further errors in separate issues.
