### ISSUE TITLE
[electron]: TypeError: Cannot read property 'fileName' of undefined error while compiling 

### ISSUE THREAD

**Issue by Schahen** [Kotlin/dukat#286]
Running `dukat` on `electron.d.ts` file from  (at least) electron@8.2.5 leads to:

```bash
/Users/shagen/dukat/node-package/build/distrib/lib/converter.js:481
        return this.astFactory.createSourceFileDeclaration(sourceFile.fileName, this.createModuleFromSourceFile(sourceFile, filter));
                                                                      ^

TypeError: Cannot read property 'fileName' of undefined
    at AstConverter.createSourceFileDeclaration (/Users/shagen/dukat/node-package/build/distrib/lib/converter.js:481:71)
    at /Users/shagen/dukat/node-package/build/distrib/lib/converter.js:168:49
    at /Users/shagen/dukat/node-package/build/distrib/lib/converter.js:23705:13
    at Map.forEach (<anonymous>)
    at DependencyBuilder.forEachDependency (/Users/shagen/dukat/node-package/build/distrib/lib/converter.js:23704:27)
    at SourceBundleBuilder.createBundle (/Users/shagen/dukat/node-package/build/distrib/lib/converter.js:167:32)
    at createSourceSet (/Users/shagen/dukat/node-package/build/distrib/lib/converter.js:176:51)
    at createBinaryStream (/Users/shagen/dukat/node-package/build/distrib/bin/dukat-cli.js:98:18)
    at cliMode (/Users/shagen/dukat/node-package/build/distrib/bin/dukat-cli.js:140:27)
    at main (/Users/shagen/dukat/node-package/build/distrib/bin/dukat-cli.js:166:24)
```

The disturbing reason behind this is that from dependencyBuilder sometimes we got dependencies that de-facto not exist. I'm not sure that this is our bug (rather than a possible  combinations of inconsistent declaration and/or possible bug in typescript API itself) but in anywise it's our bug because we still need to address this somehow

**Comment by dotCipher** [comment]
Is this related to #207 ?

**Comment by IARI** [comment]
i get the same error, running dukat on any file.

**Comment by Schahen** [comment]
Starting from `dukat@0.0.5` code translates without failure, while compilation of translated code have some issues - they will be addressed in a separate issues and linked to this one.
