### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" while translating @types/pouchdb 6.4.0

### ISSUE THREAD

**Issue by epabst** [Kotlin/dukat#326]
```
> dukat build/js/node_modules/@types/pouchdb/index.d.ts
unresolved exception
RangeError: Maximum call stack size exceeded
    at Object.getPathComponents (/usr/local/lib/node_modules/dukat/node_modules/typescript/lib/typescript.js:15547:26)
    at Object.resolvePath (/usr/local/lib/node_modules/dukat/node_modules/typescript/lib/typescript.js:15718:82)
    at Object.normalizePath (/usr/local/lib/node_modules/dukat/node_modules/typescript/lib/typescript.js:15468:19)
    at DependencyBuilder.buildDependencies (/usr/local/lib/node_modules/dukat/lib/converter.js:25868:101)
    at DependencyBuilder.buildDependencies (/usr/local/lib/node_modules/dukat/lib/converter.js:25868:30)
    at DependencyBuilder.buildDependencies (/usr/local/lib/node_modules/dukat/lib/converter.js:25868:30)
    at DependencyBuilder.buildDependencies (/usr/local/lib/node_modules/dukat/lib/converter.js:25868:30)
    at DependencyBuilder.buildDependencies (/usr/local/lib/node_modules/dukat/lib/converter.js:25868:30)
    at DependencyBuilder.buildDependencies (/usr/local/lib/node_modules/dukat/lib/converter.js:25868:30)
    at DependencyBuilder.buildDependencies (/usr/local/lib/node_modules/dukat/lib/converter.js:25868:30)
```

**Comment by epabst** [comment]
It has no error doing the translation with dukat@0.0.5.
